100 = "参数输入有误"
101 = "无效请求"
101001 = "无效请求"
101002 = "两次输入的密码一致"
102 = "未授权的请求"
102001 = "IP地址不在白名单中"
102002 = "IP地址在黑名单中"
103 = "系统维护中"
104 = "连接已断开"
105 = "未认证的请求"
105001 = "无效的登录信息"
105002 = "该用户未注册"
105003 = "该用户已被冻结"
106 = "系统错误"
107 = "系统超时"
108 = "对不起，请求太频繁，请稍后再试"
109 = "请重新登录"
110 = "系统监测到该账号异常，请稍后重试"
111 = "对不起，请不要重复请求"
