100 = "Invalid parameter"
101 = "Bad request"
101001 = "Bad gateway"
101002 = "Password not changed"
102 = "Not authorized"
102001 = "IP not in white list"
102002 = "IP in black list"
103 = "Maintenance"
104 = "Connection lost"
105 = "Not authenticated"
105001 = "Invalid sign"
105002 = "User is not registered"
105003 = "User is freezed"
106 = "Unexpected error"
107 = "Timeout"
108 = "Too many requests"
109 = "User relogin"
110 = "Risk control"
111 = "Lock action failed"
1000 = "Register failed, account exist already"
1001 = "Transaction lock control"
1002 = "Verification code error"
1003 = "Phone number error"
1004 = "Password error"
1005 = "The account is logged in"
1006 = "Being friends already"
1007 = "Friend request was refused, please retry after a hour"
1008 = "Not friends"
1009 = "The user does not exist"
