100 = "Invalid parameter"
101 = "Bad request"
101001 = "Bad gateway"
101002 = "Password not changed"
102 = "Not authorized"
102001 = "IP not in white list"
102002 = "IP in black list"
103 = "Maintenance"
104 = "Connection lost"
105 = "Not authenticated"
105001 = "Invalid sign"
105002 = "User is not registered"
105003 = "User is freezed"
106 = "Unexpected error"
107 = "Timeout"
108 = "Too many requests"
109 = "User relogin"
110 = "Risk control"
111 = "Lock action failed"
